"""Added 4 columns incl. good_work to db

Revision ID: 7186e65a51c6
Revises: e301de6b1b18
Create Date: 2022-04-24 13:38:09.230278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7186e65a51c6'
down_revision = 'e301de6b1b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('good_work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monthly_donation', sa.String(length=90), nullable=True))
        batch_op.add_column(sa.Column('registration_certificate', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('blog_link', sa.String(length=250), nullable=True))
        batch_op.alter_column('country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=90),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=90),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('blog_link')
        batch_op.drop_column('registration_certificate')
        batch_op.drop_column('monthly_donation')
        batch_op.drop_column('good_work')

    # ### end Alembic commands ###
