"""Deleted location column

Revision ID: 81265a0707a0
Revises: f04955bcd03a
Create Date: 2022-01-23 21:10:28.617957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81265a0707a0'
down_revision = 'f04955bcd03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
