"""Updated orph details 1

Revision ID: ba04f61ca58d
Revises: 9440b024466b
Create Date: 2022-01-08 16:59:19.753923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba04f61ca58d'
down_revision = '9440b024466b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orphanage', sa.Column('phone_no', sa.String(length=20), nullable=True))
    op.add_column('orphanage', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('orphanage', sa.Column('activities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orphanage', 'activities')
    op.drop_column('orphanage', 'location')
    op.drop_column('orphanage', 'phone_no')
    # ### end Alembic commands ###
