"""Added location column as JSON

Revision ID: bf9d0a8b84b9
Revises: 81265a0707a0
Create Date: 2022-01-23 21:18:59.642659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9d0a8b84b9'
down_revision = '81265a0707a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
