"""Updated orphanage details

Revision ID: c6848dd67b93
Revises: e2d98c8cdda8
Create Date: 2022-01-11 12:34:26.110956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6848dd67b93'
down_revision = 'e2d98c8cdda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orphanage', sa.Column('social_media_links', sa.JSON(), nullable=True))
    op.add_column('orphanage', sa.Column('story', sa.Text(), nullable=True))
    op.add_column('orphanage', sa.Column('money_uses', sa.Text(), nullable=True))
    op.add_column('orphanage', sa.Column('photos_links', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('orphanage', 'photos_links')
    op.drop_column('orphanage', 'money_uses')
    op.drop_column('orphanage', 'story')
    op.drop_column('orphanage', 'social_media_links')
    # ### end Alembic commands ###
