"""Added messages model

Revision ID: e2d98c8cdda8
Revises: ba04f61ca58d
Create Date: 2022-01-08 18:57:54.163273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d98c8cdda8'
down_revision = 'ba04f61ca58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_first_name'), 'message', ['first_name'], unique=False)
    op.create_index(op.f('ix_message_last_name'), 'message', ['last_name'], unique=False)
    op.add_column('orphanage', sa.Column('paypal_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orphanage', 'paypal_info')
    op.drop_index(op.f('ix_message_last_name'), table_name='message')
    op.drop_index(op.f('ix_message_first_name'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
