"""Added country column to orphanages

Revision ID: e301de6b1b18
Revises: c839b718d10b
Create Date: 2022-04-16 20:32:43.498766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e301de6b1b18'
down_revision = 'c839b718d10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
