"""Added Donations model

Revision ID: f04955bcd03a
Revises: c6848dd67b93
Create Date: 2022-01-11 17:25:31.251991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04955bcd03a'
down_revision = 'c6848dd67b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('orph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orph_id'], ['orphanage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_donation_time'), 'donation', ['donation_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_donation_time'), table_name='donation')
    op.drop_table('donation')
    # ### end Alembic commands ###
